//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Request_ID { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public int Request_Devise_ID { get; set; }
        public int Request_Defect_ID { get; set; }
        public int Request_Client_ID { get; set; }
        public string Request_Description { get; set; }
        public int Request_Status_ID { get; set; }
        public int Request_Master_ID { get; set; }
        public int Request_Time { get; set; }
        public int Request_Priory_ID { get; set; }
        public int Request_Stage_ID { get; set; }
        public string Request_Comment { get; set; }
    
        public virtual Defect Defect { get; set; }
        public virtual Device Device { get; set; }
        public virtual Priory Priory { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
