//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int Request_ID { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Device_Name { get; set; }
        public string Defect_Name { get; set; }
        public string User_Full_Name { get; set; }
        public string Status_Name { get; set; }
        public int Request_Master_ID { get; set; }
        public int Request_Time { get; set; }
        public string Priory_Name { get; set; }
        public string Stage_Name { get; set; }
        public string Request_Comment { get; set; }
    }
}
