//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_3
    {
        public int Request_ID { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public int Request_Master_ID { get; set; }
    }
}
